version: "2"
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "10001:9000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/var/www/site
    command: ["./vendor/bin/phpunit"]